### ISSUE TITLE
Использование всхе возможностей чата

### ISSUE THREAD

**Issue by FazziCLAY** [owoPeef/ChatAndTabManager#1]
Сделай кликабельные сообщения и что бы всё можно было настраивать

**Comment by owoPeef** [comment]
Клибальные - в смысле? Что именно ты имеешь в виду под этим словом

**Comment by FazziCLAY** [comment]
Чат в майнкрафте умеет показывать текст при наведении(и даже не на всё сообщение) и делать что то при нажатии на сообщение) так вот как мне это сделать через твой плагин?

**Comment by owoPeef** [comment]
А что именно нужно при наведении, например?

**Comment by FazziCLAY** [comment]
Чат в майнкрафте умеет показывать текст при наведении(и даже не на всё сообщение) и делать что то при нажатии на сообщение) так вот как мне это сделать через твой плагин?

> Клибальные - в смысле? Что именно ты имеешь в виду под этим словом

Чат в майнкрафте умеет показывать текст при наведении(и даже не на всё сообщение) и делать что то при нажатии на сообщение) так вот как мне это сделать через твой плагин?
